from xdj_sql import table,fields


@table("course_overviews_courseoverview")
class CourseoverView():
    id = fields.text()
    created = fields.date()
    modified = fields.date()
    version = fields.number()
    _location = fields.text()
    display_name = fields.text()
    display_number_with_default =fields.text()
    display_org_with_default = fields.text()
    start = fields.date()
    end = fields.date()
    advertised_start = fields.text()
    course_image_url = fields.text()
    social_sharing_url = fields.text()
    end_of_course_survey_url = fields.text()
    certificates_display_behavior = fields.text()
    certificates_show_before_end = fields.boolean()
    cert_html_view_enabled =fields.boolean()
    has_any_active_web_certificate = fields.boolean()
    cert_name_short = fields.text()
    cert_name_long = fields.text()
    lowest_passing_grade =fields.number()
    days_early_for_beta = fields.number()
    mobile_available = fields.boolean()
    visible_to_staff_only = fields.boolean()
    _pre_requisite_courses_json = fields.text()
    enrollment_start = fields.date()
    enrollment_end =fields.date()
    enrollment_domain = fields.text()
    invitation_only = fields.boolean()
    max_student_enrollments_allowed = fields.integer()
    announcement = fields.date()
    catalog_visibility = fields.text()
    course_video_url = fields.text()
    effort = fields.text()
    short_description = fields.text()
    org = fields.text()
    self_paced = fields.boolean()
    marketing_url = fields.text()
    eligible_for_financial_aid = fields.boolean()
    language = fields.text()
    certificate_available_date = fields.date()
